//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTouristik.PlugIn.OVH_V3.Search.LM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEH_ObjektInfo
    {
        public int soObjektId { get; set; }
        public int soOrtId { get; set; }
        public int soRegion { get; set; }
        public string soKurzBeschreibung { get; set; }
        public string soLangBeschreibung { get; set; }
        public string soImageLocation { get; set; }
        public string soRouteObjektId { get; set; }
        public string soRouteObjektTyp { get; set; }
        public string Pool { get; set; }
    }
}
