//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTouristik.PlugIn.OVH_V3.Search.LM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEH_UnitInfo
    {
        public int Id { get; set; }
        public int suUnitId { get; set; }
        public int suObjektId { get; set; }
        public string suKurzBeschreibung { get; set; }
        public string suLangBeschreibung { get; set; }
        public string suImageLocation { get; set; }
        public string suRouteObjektId { get; set; }
        public string suRouteObjektTyp { get; set; }
        public System.DateTime suAngebotVon { get; set; }
        public System.DateTime suAngebotBis { get; set; }
        public int suFreeUnitCount { get; set; }
        public int suMaxBelegung { get; set; }
        public int suMaxErwachsener { get; set; }
        public int suTourOperator { get; set; }
        public int suHund { get; set; }
        public string suBettwaesche { get; set; }
        public string suGeschirrspueler { get; set; }
        public int suMHGroße { get; set; }
        public int suSchlafzimmer { get; set; }
        public string suIsActive { get; set; }
        public int suLeistungstraegerId { get; set; }
        public string suSiteCode { get; set; }
        public string suOfferCode { get; set; }
        public string suAnbieterHinweis { get; set; }
        public Nullable<int> SuSort { get; set; }
        public string TourOperatorCode { get; set; }
    }
}
