//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTouristik.PlugIn.OVH_V3.Search.LM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEH_PlaceInfoSet
    {
        public int Id { get; set; }
        public string PlaceName { get; set; }
        public string RegionId { get; set; }
        public string IsInsel { get; set; }
    }
}
