//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTouristik.PlugIn.OVH_V3.Search.LM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEH_FeWoPreiseSet
    {
        public int Angebot_Id { get; set; }
        public int counter { get; set; }
        public System.DateTime Anreise { get; set; }
        public short Reisedauer { get; set; }
        public short MinPersonen { get; set; }
        public short MaxPersonen { get; set; }
        public decimal ListenPreis { get; set; }
        public decimal EndPreis { get; set; }
        public string DealCode { get; set; }
    }
}
