//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbBuchungen
    {
        public int buchID { get; set; }
        public int BuchungsNummer { get; set; }
        public string buchGuid { get; set; }
        public int buchVermieterID { get; set; }
        public int buchUnitId { get; set; }
        public System.DateTime buchAnreise { get; set; }
        public System.DateTime buchAbreise { get; set; }
        public Nullable<System.DateTime> buchBuchungsDatum { get; set; }
        public decimal buchListPreis { get; set; }
        public decimal buchVermieterRabat { get; set; }
        public decimal buchGutscheinRabat { get; set; }
        public decimal buchPreisMobilheim { get; set; }
        public decimal buchPreisEndreinung { get; set; }
        public decimal buchPreisEndBetrag { get; set; }
        public decimal buchPreisKaution { get; set; }
        public decimal buchUeberweisungBetrag { get; set; }
        public System.DateTime buchEingangDatum { get; set; }
        public string buchCampName { get; set; }
        public string buchCampOrt { get; set; }
        public string buchAnrede { get; set; }
        public string buchVornahme { get; set; }
        public string buchNachname { get; set; }
        public string buchStrasse { get; set; }
        public string buchPlzOrt { get; set; }
        public string buchLand { get; set; }
        public string buchTelefonNr { get; set; }
        public string buchHandyNr { get; set; }
        public string buchEmail { get; set; }
        public string buchAnmerkung { get; set; }
        public Nullable<System.DateTime> buchEmailActivation { get; set; }
        public string buchGutscheinCode { get; set; }
        public int buchPartnerID { get; set; }
        public int buchErwaksene { get; set; }
        public int buchKinder { get; set; }
        public string buchPortalCode { get; set; }
        public string ReisendeJson { get; set; }
        public string BookingNumber { get; set; }
    }
}
