//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbGeoLocation
    {
        public short geoTyp { get; set; }
        public int geoID { get; set; }
        public string geoName { get; set; }
        public Nullable<int> geoParent { get; set; }
    }
}
