//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgorEntities : DbContext
    {
        public IgorEntities()
            : base("name=IgorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SEH_SiteInfo> SEH_SiteInfo { get; set; }
        public virtual DbSet<SEH_UnitInfo> SEH_UnitInfo { get; set; }
        public virtual DbSet<dbBuchungen> dbBuchungens { get; set; }
        public virtual DbSet<dbGeoLocation> dbGeoLocations { get; set; }
    }
}
