//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEH_SiteInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEH_SiteInfo()
        {
            this.SEH_UnitInfo = new HashSet<SEH_UnitInfo>();
        }
    
        public int soObjektId { get; set; }
        public int soOrtId { get; set; }
        public int soRegion { get; set; }
        public string soKurzBeschreibung { get; set; }
        public string soLangBeschreibung { get; set; }
        public string soImageLocation { get; set; }
        public string soRouteObjektId { get; set; }
        public string soRouteObjektTyp { get; set; }
        public string Pool { get; set; }
        public string SiteCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEH_UnitInfo> SEH_UnitInfo { get; set; }
    }
}
